apiVersion: apps/v1
kind: Deployment
metadata:
  name: laravel-app
  namespace: mnkre-dev
spec:
  replicas: 3
  selector:
    matchLabels:
      app: laravel
  template:
    metadata:
      labels:
        app: laravel
    spec:
      containers:
        - name: laravel-app
          image: mnkre-laravel-app:latest
          ports:
            - containerPort: 80
