apiVersion: v1
kind: Service
metadata:
  name: laravel-service
  namespace: mnkre-dev
spec:
  selector:
    app: laravel
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
