- name: Configure Kubernetes Cluster
  hosts: localhost
  tasks:
    - name: Install kubectl
      shell: |
        curl -o kubectl https://amazon-eks.s3.us-west-2.amazonaws.com/1.20.4/2021-08-23/bin/linux/amd64/kubectl
        chmod +x ./kubectl
        mv ./kubectl /usr/local/bin/kubectl

    - name: Apply Kubernetes Config
      shell: |
        kubectl apply -f kubernetes/deployment.yaml
        kubectl apply -f kubernetes/service.yaml
